### ISSUE TITLE
fix MCP2515_INT

### ISSUE THREAD

**Issue by generationmake** [107-systems/l3xz-leg-ctrl-hardware#2]
### :bug: Bug Report

<p align="center">
  <a href="https://github.com/107-systems/107-Arduino-Viper"><img src="https://github.com/107-systems/.github/raw/main/logo/viper.jpg" width="20%"></a>
</p>

**Describe the bug**

we somehow managed to connect MCP2515_INT to a pin which is not capable of interrupts.

**Comment by aentinger** [comment]
That should not be oO. Ive checked ArduinoCore-samd Ehen reviewing the schematic and I remember it was a PCINT pin. Will double-check ...
________________________________
Von: generationmake ***@***.***>
Gesendet: Montag, 18. April 2022 23:44:15
An: 107-systems/l3xz-hw_leg-controller
Cc: Subscribed
Betreff: [107-systems/l3xz-hw_leg-controller] fix MCP2515_INT (Issue #2)


🐛 Bug Report

[https://github.com/107-systems/.github/raw/main/logo/viper.jpg]<https://github.com/107-systems/107-Arduino-Viper>

Describe the bug

we somehow managed to connect MCP2515_INT to a pin which is not capable of interrupts.
